services:
  # Serviço da sua aplicação Java
  app:
    build: .
    restart: on-failure
    ports:
      # Mapeia a porta 8080 do seu PC para a porta 8080 do contêiner
      - "8080:8080"
    environment:
      # Variáveis de ambiente para sua aplicação se conectar ao banco.
      # Você precisará usar estas variáveis no seu código Java.
      - DB_URL=jdbc:mysql://db:3306/rawdb
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      db:
        # Garante que o 'app' só inicia quando o 'db' estiver saudável
        condition: service_healthy

  # Serviço do banco de dados MySQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: rawdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: